# vehicle_msgs/PathService.srv
#   service type for path planner operations

# common service commands
string CMD_START=start                  # start the navigation once a path as been loaded or requested
string CMD_RESET=reset                  # abort the navigation disabling the pilot module and cancelling the current path
string CMD_HOVER=hover                  # pause the navigation (if any) and make the vehicle hold its position
string CMD_PATH=path                    # request a new path (this will produce a new path id)

Header header                           # stamp the message
string command                          # request a given fsm state

Vector6[] points                        # list of waypoints (ie. control point for navigation)
diagnostic_msgs/KeyValue[] options      # list of options (ie. additional parameters for navigation algorithms)

---------

bool result                             # the result of the service request (if false check info for errors)
string state                            # the current state of the path navigation
diagnostic_msgs/KeyValue[] info         # list of additional info about the service request
